[package]
name = "sudoku-dioxus"
version = "0.1.0"
edition = "2021"
authors = ["Jose Storopoli <jose@storopoli.io>"]
description = "Sudoku PWA with Dioxus"
license = "MIT"
readme = "README.md"

[dependencies]
[profile.release]
lto = true
