[package]
name = "sudoku-dioxus"
version = "0.1.0"
edition = "2021"
authors = ["Jose Storopoli <jose@storopoli.io>"]
description = "Sudoku PWA with Dioxus"
license = "MIT"
readme = "README.md"

[dependencies]
dioxus = "0.4"
dioxus-web = "0.4"
sudoku = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
#js-sys = "0.3"

[dev-dependencies]
dioxus-ssr = "0.4.3"
rand = "0.8"
regex = "1"

[profile.release]
lto = true
